extends:
  - stylelint-config-recommended
  - stylelint-config-standard-vue
plugins:
  - stylelint-prettier
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - tailwind
      - apply
      - variants
      - responsive
      - screen
